### ISSUE TITLE
deprecated macos runners in workflows

### ISSUE THREAD

**Issue by ttytm** [ttytm/wthrr-the-weathercrab#348]
macos-11 runner images have been deprecated.

The last time testing newer x86-64 macos runners, there were problems related to the rust-toolchain, which may have been fixed in the meantime.

**Comment by kevinmatthes** [comment]
@ttytm

I am working on this problem, right now.  As I have found out by now, ``macos-11`` does not seem to exist, anymore.  I will prepare a PR which uses ``macos-12`` as well as ``macos-13`` as replacements for the outdated ``macos-11`` setting.  As ``macos-latest`` is defined as an alias for ``macos-14``, I will just focus on the other two as we are already testing on ``macos-14`` implicitly due to the redirection.

For further information, please see https://github.com/actions/runner-images#available-images.

**Comment by ttytm** [comment]
I was aware that macos-11 was deprecated for a while announced to be removed. I was just lazy due to the toolchain issue with the newer intel runners and then didn't manage to make an update after the removal.

Thanks for the work and research.
